pipeline {
    agent any

    environment {
        def myString = 'Hello World!'
        def myNumber = 10
    }

    stages {
        stage('Demo') {
            steps {
                echo 'This is the demo stage, the build will begin...'
            }
        }

        stage('Build') {
            steps {
                echo 'Trying to build the pipline by calling the function...'
                script {
                    def result = getMyVariable(env.myString, env.myNumber.toInteger())
                    echo result
                }
            }
        }

        stage('Success') {
            steps {
                echo 'Successfully completed the build!'
            }
        }
    }
}

String getMyVariable(String text, int number) {
    return "My text is: ${text} and my number is ${number}"
}
