pipeline {
    agent any

    parameters {
        choice(choices : [
            'TEST',
            'DEV',
            'PRE_PROD',
            'PROD'
        ],
        description: 'Determine the type of environment',
        name : 'myChoiceParam')
    }

    stages {
        stage('Demo') {
            steps {
                echo 'This is the Demo Stage!'
            }
        }

        stage('Build') {
            steps {
                echo "This is the build stage with the param value set to ${params.myChoiceParam}"
            }
        }
    }
}
