pipeline {
    agent any

    environment {
        def myString = 'Hello World!'
        def myNumber = 10
        def myBool = true
    }

    stages {
        stage('Demo') {
            steps {
                echo "My String - ${myString}"
                echo "My Number - ${myNumber}"
                echo "My Boolean - ${myBool}"
            }
        }
    }
}
